version: '3'

services:
  mongo_main:
    image: 'bitnami/mongodb:latest'
    container_name: mongo_main
    restart: always
    ports:
      - 27000:27017
    environment:
      - MONGODB_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGODB_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGODB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGODB_DATABASE=achieve
    volumes:
      - /tmp/mongo:/bitnami
    networks:
      - mongo_net
  
volumes:
  mongo_main_data: {}
  mongo_main_config: {}

networks:
  mongo_net:
